- name: play variables
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: print play variable
      ansible.builtin.debug:
        msg: URL {{ URL }}


- name: play variables from files
  hosts: localhost
  ## var_files works only under play level variables
  vars_files:
    - var.yml
  tasks:
    - name: print play variable from files
      ansible.builtin.debug:
        msg: URL {{ URL }}

- name: task level variables
  hosts: localhost
  tasks:
    - name: print play variable
      vars: ## these vars are only for this task, next task on same play cannot work
        URL: task.example.com
      ansible.builtin.debug:
        msg: URL {{ URL }}

- name: vars from inventory
  hosts: all
  tasks:
    - name: print play variable from inventory
      ansible.builtin.debug:
        msg: "URL = {{ URL }}, Hostname of the server = {{ ansible_hostname }}"

- name: register a variable
  hosts: localhost
  tasks:
    - name: get uptime output
      ansible.builtin.shell: uptime
      register: out

    - name: print out
      ansible.builtin.debug:
        msg: "{{ out }}"

    - name: declare a variable
      ansible.builtin.set_fact:
        status: "{{ out.rc }}"

    - name: print out status
      ansible.builtin.debug:
        msg: "{{ status }}"